FROM drupal:8

# Install Drush
RUN curl -sS https://getcomposer.org/installer | php
RUN mv composer.phar /usr/local/bin/composer
RUN composer global require drush/drush:^8.1.10
RUN ln -s /root/.composer/vendor/drush/drush/drush /bin/drush

# Install mysql client.
RUN apt-get update && apt-get upgrade -y
RUN apt-get install -y mysql-client

# Add some files to our container. See each individual file for details.
ADD docker-resources/scripts /scripts
ADD docker-resources/site-php /var/www/site-php

# Make sure opcache is disabled during development so that our changes
# to PHP are reflected immediately.
RUN echo 'opcache.enable=0' >> /usr/local/etc/php/php.ini

EXPOSE 80
